<?php

namespace Example\Thing\Intangible;

use Example\Thing\Intangible;

/**
 * Service
 * http://schema.org/Service
 */
class Service extends Intangible
{

    /**
     * A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)
     *
     * @var ServiceChannel
     */
    private $availableChannel;

    /**
     * The tangible thing generated by the service, e.g. a passport, permit, etc.
     *
     * @var Thing
     */
    private $produces;

    /**
     * The organization or agency that is providing the service.
     *
     * @var Organization|Person
     */
    private $provider;

    /**
     * The geographic area where the service is provided.
     *
     * @var AdministrativeArea
     */
    private $serviceArea;

    /**
     * The audience eligible for this service.
     *
     * @var Audience
     */
    private $serviceAudience;

    /**
     * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     *
     * @var String
     */
    private $serviceType;

    /**
     * schema.org url
     */
    private $url = "http://schema.org/Service";

    public function getavailableChannel()
    {
        return $this->availableChannel;
    }

    public function setavailableChannel($availableChannel)
    {
        $this->availableChannel = $availableChannel;
        return $this;
    }

    public function getproduces()
    {
        return $this->produces;
    }

    public function setproduces($produces)
    {
        $this->produces = $produces;
        return $this;
    }

    public function getprovider()
    {
        return $this->provider;
    }

    public function setprovider($provider)
    {
        $this->provider = $provider;
        return $this;
    }

    public function getserviceArea()
    {
        return $this->serviceArea;
    }

    public function setserviceArea($serviceArea)
    {
        $this->serviceArea = $serviceArea;
        return $this;
    }

    public function getserviceAudience()
    {
        return $this->serviceAudience;
    }

    public function setserviceAudience($serviceAudience)
    {
        $this->serviceAudience = $serviceAudience;
        return $this;
    }

    public function getserviceType()
    {
        return $this->serviceType;
    }

    public function setserviceType($serviceType)
    {
        $this->serviceType = $serviceType;
        return $this;
    }

}
