<?php
/**
 * This is an auto generated file.
 * You are encouraged to edit the script below:
 * https://github.com/robin-zhao/rzSchemaorgPHPConverter/
 */

namespace Robinzhao\SchemaOrg\Thing\Intangible;

use Robinzhao\SchemaOrg\Thing\Intangible;

/**
 * Service
 * http://schema.org/Service
 */
class Service extends Intangible
{

    /**
     * A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)
     *
     * @var Robinzhao\SchemaOrg\Thing\Intangible\ServiceChannel
     */
    protected $availableChannel;

    /**
     * The tangible thing generated by the service, e.g. a passport, permit, etc.
     *
     * @var Robinzhao\SchemaOrg\Thing
     */
    protected $produces;

    /**
     * The organization or agency that is providing the service.
     *
     * @var Robinzhao\SchemaOrg\Thing\Organization|Robinzhao\SchemaOrg\Thing\Person
     */
    protected $provider;

    /**
     * The geographic area where the service is provided.
     *
     * @var Robinzhao\SchemaOrg\Thing\Place\AdministrativeArea
     */
    protected $serviceArea;

    /**
     * The audience eligible for this service.
     *
     * @var Robinzhao\SchemaOrg\Thing\Intangible\Audience
     */
    protected $serviceAudience;

    /**
     * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     *
     * @var String
     */
    protected $serviceType;

    /**
     * schema.org context url
     * @var String
     */
    protected $context = "http://schema.org/Service";

    /**
     * @return Robinzhao\SchemaOrg\Thing\Intangible\ServiceChannel
     */
    public function getAvailableChannel()
    {
        return $this->availableChannel;
    }

    /**
     * @param $availableChannel Robinzhao\SchemaOrg\Thing\Intangible\ServiceChannel
     */
    public function setAvailableChannel($availableChannel)
    {
        $this->availableChannel = $availableChannel;
        return $this;
    }

    /**
     * @return Robinzhao\SchemaOrg\Thing
     */
    public function getProduces()
    {
        return $this->produces;
    }

    /**
     * @param $produces Robinzhao\SchemaOrg\Thing
     */
    public function setProduces($produces)
    {
        $this->produces = $produces;
        return $this;
    }

    /**
     * @return Robinzhao\SchemaOrg\Thing\Organization|Robinzhao\SchemaOrg\Thing\Person
     */
    public function getProvider()
    {
        return $this->provider;
    }

    /**
     * @param $provider Robinzhao\SchemaOrg\Thing\Organization|Robinzhao\SchemaOrg\Thing\Person
     */
    public function setProvider($provider)
    {
        $this->provider = $provider;
        return $this;
    }

    /**
     * @return Robinzhao\SchemaOrg\Thing\Place\AdministrativeArea
     */
    public function getServiceArea()
    {
        return $this->serviceArea;
    }

    /**
     * @param $serviceArea Robinzhao\SchemaOrg\Thing\Place\AdministrativeArea
     */
    public function setServiceArea($serviceArea)
    {
        $this->serviceArea = $serviceArea;
        return $this;
    }

    /**
     * @return Robinzhao\SchemaOrg\Thing\Intangible\Audience
     */
    public function getServiceAudience()
    {
        return $this->serviceAudience;
    }

    /**
     * @param $serviceAudience Robinzhao\SchemaOrg\Thing\Intangible\Audience
     */
    public function setServiceAudience($serviceAudience)
    {
        $this->serviceAudience = $serviceAudience;
        return $this;
    }

    /**
     * @return String
     */
    public function getServiceType()
    {
        return $this->serviceType;
    }

    /**
     * @param $serviceType String
     */
    public function setServiceType($serviceType)
    {
        $this->serviceType = $serviceType;
        return $this;
    }

}
