<?php
/**
 * This is an auto generated file.
 * You are encouraged to edit the script below:
 * https://github.com/robin-zhao/rzSchemaorgPHPConverter/
 */

namespace Robinzhao\SchemaOrg\Thing\Intangible;

use Robinzhao\SchemaOrg\Thing\Intangible;

/**
 * Service
 * http://schema.org/Service
 */
class Service extends Intangible
{

    /**
     * A means of accessing the service (e.g. a phone bank, a web site, a location, etc.)
     *
     * @var Robinzhao\SchemaOrg\Thing\Intangible\ServiceChannel
     */
    public $availableChannel;

    /**
     * The tangible thing generated by the service, e.g. a passport, permit, etc.
     *
     * @var Robinzhao\SchemaOrg\Thing
     */
    public $produces;

    /**
     * The organization or agency that is providing the service.
     *
     * @var Robinzhao\SchemaOrg\Thing\Organization|Robinzhao\SchemaOrg\Thing\Person
     */
    public $provider;

    /**
     * The geographic area where the service is provided.
     *
     * @var Robinzhao\SchemaOrg\Thing\Place\AdministrativeArea
     */
    public $serviceArea;

    /**
     * The audience eligible for this service.
     *
     * @var Robinzhao\SchemaOrg\Thing\Intangible\Audience
     */
    public $serviceAudience;

    /**
     * The type of service being offered, e.g. veterans' benefits, emergency relief, etc.
     *
     * @var String
     */
    public $serviceType;

    /**
     * schema.org context url
     * @var String
     */
    public $context = "http://schema.org/Service";

    /**
     * @param $availableChannel Robinzhao\SchemaOrg\Thing\Intangible\ServiceChannel
     */
    public function addAvailableChannel($availableChannel)
    {
        $this->availableChannel []= $availableChannel;
        return $this;
    }

    /**
     * @param $produces Robinzhao\SchemaOrg\Thing
     */
    public function addProduces($produces)
    {
        $this->produces []= $produces;
        return $this;
    }

    /**
     * @param $provider Robinzhao\SchemaOrg\Thing\Organization|Robinzhao\SchemaOrg\Thing\Person
     */
    public function addProvider($provider)
    {
        $this->provider []= $provider;
        return $this;
    }

    /**
     * @param $serviceArea Robinzhao\SchemaOrg\Thing\Place\AdministrativeArea
     */
    public function addServiceArea($serviceArea)
    {
        $this->serviceArea []= $serviceArea;
        return $this;
    }

    /**
     * @param $serviceAudience Robinzhao\SchemaOrg\Thing\Intangible\Audience
     */
    public function addServiceAudience($serviceAudience)
    {
        $this->serviceAudience []= $serviceAudience;
        return $this;
    }

    /**
     * @param $serviceType String
     */
    public function addServiceType($serviceType)
    {
        $this->serviceType []= $serviceType;
        return $this;
    }

}
